apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer-api-service
  namespace: wazuh
  labels:
    app: wazuh-indexer
spec:
  type: LoadBalancer
  selector:
    app: wazuh-indexer
  ports:
    - name: indexer-rest
      port: 9200
      targetPort: 9200
