
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: your-namespace  # Replace with the namespace you want to use
spec:
  acme:
    # You must replace this email address with your own.
    email: info@puffinsecurity.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
