apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-indexer-admin-cert
  namespace: wazuh
spec:
  secretName: wazuh-indexer-admin-cert-secret
  duration: 87600h
  commonName: "admin"
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: wazuh-ca-issuer
    kind: Issuer
