apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wazuh-indexer-root-ca
  namespace: wazuh
spec:
  secretName: wazuh-indexer-root-ca-secret
  isCA: true
  commonName: "root-ca"
  privateKey:
    rotationPolicy: Always
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
