apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds wazuh namespace to all resources.
namespace: wazuh

configMapGenerator:
  - name: wazuh-indexer-conf
    files:
      - wazuh-indexer/conf/opensearch.yml
      - wazuh-indexer/conf/internal_users.yml
  - name: wazuh-managers-conf
    files:
      - wazuh-managers/worker/worker.conf
      - wazuh-managers/master/master.conf
  - name: wazuh-dashboard-conf
    files:
      - wazuh-dashboard/conf/opensearch_dashboards.yml

resources:
  - base/wazuh-ns.yaml
  - base/storage-class.yaml
